VIA_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
COMBO_ENABLE = yes
TD_LSFT_CAPSLOCK_ENABLE = yes
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = no
ENCODER_DEFAULTACTIONS_ENABLE = yes

COLEMAK_LAYER_ENABLE = no  #Enable Colemak layer / set to no to disable
INVERT_NUMLOCK_INDICATOR = yes